name: CI/CD Pipeline Front End

on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Build and Deploy on Server
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Extract version from Git tag
        id: vars
        run: echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV

        
      - name: Build and Deploy via SSH
        uses: appleboy/ssh-action@v0.1.4
        env:
          VERSION: ${{ env.VERSION }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 25
          script: |
            cd /var/local/memoo-vue-pinia
            sudo git pull
            sudo npm i
            sudo npm run build
            sudo cp -r dist/* build/dist
            cd build
            docker build --no-cache -t memoo-client:${{ env.VERSION }} .
            docker stop container-client || true
            docker rm container-client || true
            docker run -d --name container-client --restart always -p 4500:4500 memoo-client:${{ env.VERSION }}